In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.notebook_repr_html', False)
pd.set_option('display.max_columns', 8)
pd.set_option('display.max_rows', 8)

In [2]:
np.random.seed(1)

In [3]:
s = pd.Series(np.random.randn(100))

In [4]:
s

0     1.624345
1    -0.611756
2    -0.528172
3    -1.072969
        ...   
96   -0.343854
97    0.043597
98   -0.620001
99    0.698032
dtype: float64

In [5]:
s[2]

-0.5281717522634557

In [6]:
s[[2,3,10]]

2    -0.528172
3    -1.072969
10    1.462108
dtype: float64

In [7]:
s[3:8]

3   -1.072969
4    0.865408
5   -2.301539
6    1.744812
7   -0.761207
dtype: float64

In [48]:
s.index

RangeIndex(start=0, stop=10, step=1)

In [9]:
s.values

array([ 1.62434536, -0.61175641, -0.52817175, -1.07296862,  0.86540763,
       -2.3015387 ,  1.74481176, -0.7612069 ,  0.3190391 , -0.24937038,
        1.46210794, -2.06014071, -0.3224172 , -0.38405435,  1.13376944,
       -1.09989127, -0.17242821, -0.87785842,  0.04221375,  0.58281521,
       -1.10061918,  1.14472371,  0.90159072,  0.50249434,  0.90085595,
       -0.68372786, -0.12289023, -0.93576943, -0.26788808,  0.53035547,
       -0.69166075, -0.39675353, -0.6871727 , -0.84520564, -0.67124613,
       -0.0126646 , -1.11731035,  0.2344157 ,  1.65980218,  0.74204416,
       -0.19183555, -0.88762896, -0.74715829,  1.6924546 ,  0.05080775,
       -0.63699565,  0.19091548,  2.10025514,  0.12015895,  0.61720311,
        0.30017032, -0.35224985, -1.1425182 , -0.34934272, -0.20889423,
        0.58662319,  0.83898341,  0.93110208,  0.28558733,  0.88514116,
       -0.75439794,  1.25286816,  0.51292982, -0.29809284,  0.48851815,
       -0.07557171,  1.13162939,  1.51981682,  2.18557541, -1.39

In [10]:
s2 = pd.Series([1,2,3,4], index=['a', 'b', 'c', 'd'])

In [11]:
s2

a    1
b    2
c    3
d    4
dtype: int64

In [12]:
s2 = pd.Series({'a':1, 'b':2, 'c':3, 'd':4})

In [13]:
s2

a    1
b    2
c    3
d    4
dtype: int64

In [14]:
s = pd.Series([10, 0, 1, 1, 2, 3, 4, 5, 6, np.nan])

In [15]:
len(s)

10

In [16]:
s.shape

(10,)

In [17]:
s.count()

9

In [18]:
s.unique()

array([ 10.,   0.,   1.,   2.,   3.,   4.,   5.,   6.,  nan])

In [19]:
s.value_counts()

1.0     2
10.0    1
6.0     1
5.0     1
4.0     1
3.0     1
2.0     1
0.0     1
dtype: int64

In [21]:
s3 = pd.Series([1,2,3,4], index=['a', 'b', 'c', 'd'])

In [22]:
s4 = pd.Series([4,3,2,1], index=['d', 'c', 'b', 'a'])

In [23]:
s3

a    1
b    2
c    3
d    4
dtype: int64

In [24]:
s4

d    4
c    3
b    2
a    1
dtype: int64

In [25]:
s3+s4

a    2
b    4
c    6
d    8
dtype: int64

In [26]:
pd.DataFrame([[10,11], [20,21]])

    0   1
0  10  11
1  20  21

In [28]:
df1 = pd.DataFrame([pd.Series(np.arange(10,15)),
                    pd.Series(np.arange(15,20))])

In [29]:
df1

    0   1   2   3   4
0  10  11  12  13  14
1  15  16  17  18  19

In [30]:
df1.shape

(2, 5)

In [31]:
df = pd.DataFrame(np.array([[10,11], [20,21]]),
                  columns=['a', 'b'])

In [32]:
df

    a   b
0  10  11
1  20  21

In [33]:
df.columns

Index(['a', 'b'], dtype='object')

In [34]:
df.columns = ['c1', 'c2']

In [35]:
df

   c1  c2
0  10  11
1  20  21

In [38]:
df = pd.DataFrame(np.array([[0,1], [2,3]]),
                  columns=['c1', 'c2'],
                  index=['r1', 'r2'])

In [39]:
df

    c1  c2
r1   0   1
r2   2   3

In [40]:
df.index

Index(['r1', 'r2'], dtype='object')

In [41]:
df.values

array([[0, 1],
       [2, 3]])

In [42]:
s1 = pd.Series(np.arange(1,6,1))
s2 = pd.Series(np.arange(6,11,1))
pd.DataFrame({'c1': s1, 'c2': s2})

   c1  c2
0   1   6
1   2   7
2   3   8
3   4   9
4   5  10

In [43]:
s3 = pd.Series(np.arange(12, 14), index=[1, 2])

In [44]:
pd.DataFrame({'c1': s1, 'c2': s2, 'c3': s3})

   c1  c2    c3
0   1   6   NaN
1   2   7  12.0
2   3   8  13.0
3   4   9   NaN
4   5  10   NaN

In [45]:
sp500 = pd.read_csv("../data/sp500.csv", index_col='Symbol', usecols=[0, 2, 3, 7])

In [46]:
sp500.head()

                        Sector   Price  Book Value
Symbol                                            
MMM                Industrials  141.14      26.668
ABT                Health Care   39.60      15.573
ABBV               Health Care   53.95       2.954
ACN     Information Technology   79.79       8.326
ACE                 Financials  102.91      86.897

In [47]:
sp500.index

Index(['MMM', 'ABT', 'ABBV', 'ACN', 'ACE', 'ACT', 'ADBE', 'AES', 'AET', 'AFL',
       ...
       'XEL', 'XRX', 'XLNX', 'XL', 'XYL', 'YHOO', 'YUM', 'ZMH', 'ZION', 'ZTS'],
      dtype='object', name='Symbol', length=500)

In [49]:
sp500[[1,2]].head(3)

         Price  Book Value
Symbol                    
MMM     141.14      26.668
ABT      39.60      15.573
ABBV     53.95       2.954

In [50]:
sp500[[1]].head(3)

         Price
Symbol        
MMM     141.14
ABT      39.60
ABBV     53.95

In [51]:
sp500['Price'].head(3)

Symbol
MMM     141.14
ABT      39.60
ABBV     53.95
Name: Price, dtype: float64

In [52]:
sp500[['Price', 'Sector']]

         Price                  Sector
Symbol                                
MMM     141.14             Industrials
ABT      39.60             Health Care
ABBV     53.95             Health Care
ACN      79.79  Information Technology
...        ...                     ...
YUM      74.77  Consumer Discretionary
ZMH     101.84             Health Care
ZION     28.43              Financials
ZTS      30.53             Health Care

[500 rows x 2 columns]

In [53]:
sp500[:3]

             Sector   Price  Book Value
Symbol                                 
MMM     Industrials  141.14      26.668
ABT     Health Care   39.60      15.573
ABBV    Health Care   53.95       2.954

In [54]:
sp500['XYL':'YUM']

                        Sector  Price  Book Value
Symbol                                           
XYL                Industrials  38.42      12.127
YHOO    Information Technology  35.02      12.768
YUM     Consumer Discretionary  74.77       5.147

In [56]:
sp500.loc['MMM']

Sector        Industrials
Price              141.14
Book Value         26.668
Name: MMM, dtype: object

In [58]:
sp500.loc[['MMM', 'MSFT']]

                        Sector   Price  Book Value
Symbol                                            
MMM                Industrials  141.14      26.668
MSFT    Information Technology   40.12      10.584

In [59]:
sp500.iloc[[0,2]]

             Sector   Price  Book Value
Symbol                                 
MMM     Industrials  141.14      26.668
ABBV    Health Care   53.95       2.954

In [60]:
sp500.index.get_loc('MMM')

0

In [61]:
sp500.index.get_loc('A')

10

In [62]:
sp500.iloc[[0,10]]

             Sector   Price  Book Value
Symbol                                 
MMM     Industrials  141.14      26.668
A       Health Care   56.18      16.928

In [63]:
sp500.at['MMM', 'Price']

141.13999999999999

In [64]:
sp500.iat[0, 1]

141.13999999999999

In [65]:
sp500.Price < 100

Symbol
MMM     False
ABT      True
ABBV     True
ACN      True
        ...  
YUM      True
ZMH     False
ZION     True
ZTS      True
Name: Price, dtype: bool

In [66]:
sp500[sp500.Price < 100]

                        Sector  Price  Book Value
Symbol                                           
ABT                Health Care  39.60      15.573
ABBV               Health Care  53.95       2.954
ACN     Information Technology  79.79       8.326
ADBE    Information Technology  64.30      13.262
...                        ...    ...         ...
YHOO    Information Technology  35.02      12.768
YUM     Consumer Discretionary  74.77       5.147
ZION                Financials  28.43      30.191
ZTS                Health Care  30.53       2.150

[407 rows x 3 columns]

In [68]:
sp500[(sp500.Price < 10) & (sp500.Price > 0)][['Price']]

        Price
Symbol       
FTR      5.81
HCBK     9.80
HBAN     9.10
SLM      8.82
WIN      9.38

In [69]:
np.random.seed(123456)

In [71]:
df = pd.DataFrame(np.random.randn(5, 4),
                  columns=['A', 'B', 'C', 'D'])

In [73]:
df

          A         B         C         D
0  0.271860 -0.424972  0.567020  0.276232
1 -1.087401 -0.673690  0.113648 -1.478427
2  0.524988  0.404705  0.577046 -1.715002
3 -1.039268 -0.370647 -1.157892 -1.344312
4  0.844885  1.075770 -0.109050  1.643563

In [74]:
df*2

          A         B         C         D
0  0.543720 -0.849945  1.134041  0.552464
1 -2.174801 -1.347379  0.227297 -2.956853
2  1.049975  0.809410  1.154092 -3.430004
3 -2.078537 -0.741294 -2.315785 -2.688624
4  1.689770  2.151540 -0.218100  3.287126

In [76]:
df - df.iloc[0]

          A         B         C         D
0  0.000000  0.000000  0.000000  0.000000
1 -1.359261 -0.248717 -0.453372 -1.754659
2  0.253128  0.829678  0.010026 -1.991234
3 -1.311128  0.054325 -1.724913 -1.620544
4  0.573025  1.500742 -0.676070  1.367331

In [77]:
subframe = df[1:4][['B', 'C']]

In [78]:
subframe

          B         C
1 -0.673690  0.113648
2  0.404705  0.577046
3 -0.370647 -1.157892

In [79]:
df - subframe

    A    B    C   D
0 NaN  NaN  NaN NaN
1 NaN  0.0  0.0 NaN
2 NaN  0.0  0.0 NaN
3 NaN  0.0  0.0 NaN
4 NaN  NaN  NaN NaN

In [80]:
a_col = df['A']

In [81]:
df.sub(a_col, axis=0)

     A         B         C         D
0  0.0 -0.696832  0.295160  0.004372
1  0.0  0.413711  1.201049 -0.391026
2  0.0 -0.120282  0.052058 -2.239990
3  0.0  0.668622 -0.118624 -0.305043
4  0.0  0.230885 -0.953935  0.798678

In [82]:
np.random.seed(1)

In [83]:
s = pd.Series(np.random.randn(5))

In [84]:
s

0    1.624345
1   -0.611756
2   -0.528172
3   -1.072969
4    0.865408
dtype: float64

In [85]:
s.index = ['a', 'b', 'c', 'd', 'e']

In [86]:
s

a    1.624345
b   -0.611756
c   -0.528172
d   -1.072969
e    0.865408
dtype: float64

In [87]:
s2 = s.reindex(['a', 'c', 'e', 'g'])

In [88]:
s2

a    1.624345
c   -0.528172
e    0.865408
g         NaN
dtype: float64

In [89]:
s1 = pd.Series([0, 1, 2], index=[0, 1, 2])

In [90]:
s2 = pd.Series([3, 4, 5], index=['0', '1', '2'])

In [91]:
s1 + s2

0   NaN
1   NaN
2   NaN
0   NaN
1   NaN
2   NaN
dtype: float64

In [92]:
s2.index = s2.index.values.astype(int)

In [93]:
s1 + s2

0    3
1    5
2    7
dtype: int64

In [94]:
s2 = s.copy()

In [95]:
s2.reindex(['a', 'f'], fill_value=0)

a    1.624345
f    0.000000
dtype: float64

In [96]:
s3 = pd.Series(['red', 'green', 'blue'], index=[0, 3, 5])

In [97]:
s3

0      red
3    green
5     blue
dtype: object

In [98]:
s3.reindex(np.arange(0,7), method='ffill')

0      red
1      red
2      red
3    green
4    green
5     blue
6     blue
dtype: object

In [99]:
s3.reindex(np.arange(0,7), method='bfill')

0      red
1    green
2    green
3    green
4     blue
5     blue
6      NaN
dtype: object